---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 

  playbooks: 
    sshkey: false 
    ssh: false
    vscode: false
    terminator: false
    zsh: false
    ohmyzsh: false 
    spotify: false
    java: false 
    git: false
    gitlfs: false
    tig: false
    maven: false 
    golang: false 
    nodejs: false 
    yarn: false
    bazel: false
    rvm: false
    intellij: false 
    docker: false 
    google_cloud_sdk: false
    redis: false
    postman: false
    protobuf: false 
    zoom: false
    forticlient: false
    slack: false
    beyondcompare: false
    chrome: false
    firefox: false
    vlc: false
    flameshot: false
    htop: false
    keepassxc: false
    virtualbox: false
    pcloud: false

  tools:
    ohmyzsh:
      theme: frisk
      plugins:
        - gitfast
        - docker
        - docker-compose
        - helm
        - kubectl
        - mvn
        - ansible
        - golang
        - node
        - python
        - tig
        - rvm
        - ruby
        - rails
    java: 
      versions:
        - name: 8
          version: '8'
          default: no
        - name: 11 
          version: '11'
          default: yes
    gitlfs:
      version: '2.13.2'
    tig:
      version: '2.5.3'
    maven:
      version: '3.6.3'
    bazel:
      version: '4.0.0'
      sha256: 'sha256:7bee349a626281fc8b8d04a7a0b0358492712377400ab12533aeb39c2eb2b901'
    golang:
      version: '1.16.2'
      sha256sum: '542e936b19542e62679766194364f45141fde55169db2d8d01046555ca9eb4b8'
      path: '$HOME/workspace-go'
    node:
      version: '14.x'
    rvm:
      ruby:
        versions: 
          - ruby
          - 2.6.6
    docker_compose:
      version: '1.26.0'
    pcloud: ## GET THE URL ON THE PCLOUD SITE. THE DOWNLOAD LINK HAS AN EXPIRATION DATE ##
      url: 
    google_cloud_sdk:
      version: '332.0.0'
      components: pubsub-emulator app-engine-java beta
    protobuf:
      version: '3.10.0'
    slack:
      version: '4.14.0'
    forticlient:
      version: '6.4.3.0959'
    beyondcompare:
      version: '4.3.7.25118'
    intellij:
      version: '2020.2.4'
      edition: ultimate # ultimate or community
      # You can get the sha256 at this link https://confluence.jetbrains.com/display/IDEADEV/Latest+builds or at external_roles/gantsign.intellij/vars/versions
      sha256: 'd1d0b8300a958116acdb1fde4514ca27d64e329375a2c0402c4eda18c0e18672'