---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 
  os: 
    wallpaper_name: falcon.jpg
    greeter_background_name: soyuz.jpg
    lock_after: 30
    keyboard_shortcuts:
      - shortcut: "<Alt><Super>Down"
        action: "amixer set Master 5%-"
      - shortcut: "<Alt><Super>Up"
        action: "amixer set Master 5%+"
      - shortcut: "<Alt><Super>Right"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
      - shortcut: "<Alt><Super>Left"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
      - shortcut: "<Alt><Super>Return"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
      - shortcut: "<Super>l"
        action: "xflock4"

  playbooks: 
    sshkey: false 
    ssh: false
    wallpaper: false
    display_manager: false
    keyboard_shortcuts: false
    autolock: false
    packages: false 
    packages_dpkg: false
    vscode: false
    ohmyzsh: false 
    expressvpn: false 
    spotify: false
    java: false 
    git: false 
    tig: false
    maven: false 
    bazel: false
    golang: false 
    nodejs: false 
    intellij: false
    pipenv: false
    docker: false 
    vitualbox: false 
    toggl: false
    google_cloud_sdk: false
    gradle: false 
    atom: false
    sublime: false
    eclipse: false 
    protobuf: false 
    robo3t: false 
    awscli: false
    redis_desktop_manager: false
    kafkatool: false

  tools:
    codestats: ##### CHANGE ME #####
      api_key: 
    expressvpn:
      version: 2.4.4.19-1
    java: 
      versions:
        - name: default # DO NOT CHANGE THE NAME, USED BY INTELLIJ
          version: '8'
          default: yes
        # - name: latest 
        #   version: '13'
        #   default: no
    tig:
      version: '2.5.0'
    maven:
      version: '3.6.3'
    bazel:
      version: '2.2.0'
      sha256: 'sha256:b2f002ea0e6194a181af6ac84cd94bd8dc797722eb2354690bebac92dda233ff'
    golang:
      version: '1.13.4'
      sha256sum: '692d17071736f74be04a72a06dab9cac1cd759377bd85316e52b2227604c004c'
      path: '$HOME/workspace-go'
    node:
      version: '13.x'
    intellij:
      version: '2019.3.3'
      sha256: 'a71b367f36e528bed8be170a7676372b58b2df1bc572f611194efa4104c4b0d6'
      default_jdk: '8'
      style_guide_name: GoogleStyle - Custom
      style_guide_path: 'https://raw.githubusercontent.com/kamylaep/code-style/master/intellij-java-google-style-custom.xml'
      plugins:
        - Docker
        - org.jetbrains.plugins.go
        - com.dmarcotte.handlebars
        - Karma
        - com.jetbrains.plugins.meteor
        - NodeJS
        - Pythonid
        - org.jetbrains.plugins.ruby
        - org.intellij.scala
        - net.codestats.plugin.atom.intellij
        - com.arasthel.groovy.override-completion
        - InspectorGroovy
        #- Spock Framework Enhancements
        - MavenRunHelper
        - com.dubreuia
        - Lombook Plugin
        - Key Promoter X
        - com.yiycf.plugins.mavenDependencyHelper
        - com.octogog.idea.bazel-build-formatter
        - com.google.idea.bazel.ijwb
      plugins_disabled:
        - Ant Tracer Plugin
        - AntSupport
        - CFML Support
        - ClearcasePlugin
        - CloudBees
        - CloudFoundry
        - com.intellij.drools
        - com.intellij.flex
        - com.intellij.jboss.arquillian
        - com.intellij.jboss.core
        - com.intellij.jbpm
        - com.intellij.seam
        - com.intellij.seam.pageflow
        - com.intellij.seam.pages
        - com.intellij.struts2
        - com.intellij.tapestry
        - com.jetbrains.plugins.asp
        - CVS
        - DevKit
        - Geronimo
        - GlassFish
        - hg4idea
        - J2ME
        - JBoss
        - JSR45Plugin
        - OpenShift
        - org.jetbrains.plugins.javaFX
        - org.jetbrains.plugins.rest
        - PerforceDirectPlugin
        - Resin
        - StrutsAssistant
        - Subversion
        - TFS
        - Weblogic
        - WebSphere
        - ZKM
    docker_compose:
      version: '1.25.4'
    toggl:
      version: '7.5.50'
    google_cloud_sdk:
      version: '282.0.0'
      components: pubsub-emulator app-engine-java beta
    gradle:
      version: '5.6.2'
    eclipse:
      version: '2019-12'
      edition: 'jee'
      release: 'R'
    protobuf:
      version: '3.6.1'
    robo3t:
      version: '1.3.1'
    awscli: ##### CHANGE ME #####
      aws_region: 
      aws_access_key_id: 
      aws_secret_access_key: 
    kafkatool:
      url: http://www.kafkatool.com/download2/kafkatool.sh

  packages_debian: 
    - baobab
    - caja
    - chromium-browser
    - firefox
    - flameshot
    - htop
    - keepassxc
    - python3-pip
    - remmina
    - terminator
    - transmission
    - vim
    - vlc
    - zsh
  
  packages_dpkg:
    - https://www.scootersoftware.com/bcompare-4.3.3.24545_amd64.deb
    - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
    - https://download.nomachine.com/download/6.9/Linux/nomachine_6.9.2_1_amd64.deb
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.3.2-amd64.deb