---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks, it must be the same one used to login into your computer
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 

  playbooks: 
    sshkey: false 
    ssh: false
    vscode: false
    git: false
    terminator: false
    zsh: false
    ohmyzsh: false 
    tmux: false
    spotify: false
    java: false 
    tig: false
    maven: false 
    golang: false
    intellij: false 
    docker: true 
    pcloud: false
    postman: false
    beyondcompare: false
    chrome: false
    firefox: false
    vlc: false
    flameshot: false
    htop: false
    virtualbox: false
    solaar: false
    python: false
    jq: false

  tools:
    ohmyzsh:
      theme: 
        name: "powerlevel10k/powerlevel10k"
        link: https://github.com/romkatv/powerlevel10k.git
      plugins:
        - gitfast
        - git
        - docker
        - docker-compose
        - zsh-syntax-highlighting
        - zsh-autosuggestions

    java: 
      # Intellij's playbook uses both version, so don't remove them
      versions:
        - name: 8
          version: '8'
          default: no
        - name: 11 
          version: '11'
          default: no
        - name: 21 
          version: '21'
          default: yes
    tig:
      version: '2.5.4'
    maven:
      version: '3.9.1'
    golang:
      version: '1.20.5'
      sha256sum: 'd7ec48cde0d3d2be2c69203bc3e0a44de8660b9c09a6e85c4732a3f7dc442612'
      path: '$HOME/workspace-go'
    docker_compose:
      version: 'v2,26,1'
    pcloud: ## GET THE URL ON THE PCLOUD SITE. THE DOWNLOAD LINK HAS AN EXPIRATION DATE ##
      url: https://p-def7.pcloud.com/cBZQGMwxUZhuVWap7ZZZ8yzG7kZ2ZZ8yLZkZ5hhxVZcLZCFZbHZvRZVFZtFZwLZ1FZgRZTHZF4ZSLZRQZMRZ0AMJ0ZtRjmoDnPl1p7JO8oDQposLk2aWDX/pcloud
    beyondcompare:
      version: '4.4.7.28397'
    intellij:
      version: '2024.1.1'
      edition: community # ultimate or community
      sha256: '4d4221630c4d1dcb9f198370f82d9364014a4a624684ad8b3958be9f01eb656a'
      default_jdk: '21'
      style_guide_name: 'GoogleStyle - Custom'
      style_guide_path: 'https://raw.githubusercontent.com/kamylaep/code-style/master/intellij-java-google-style-custom.xml'
      plugins: 
        - org.intellij.scala
        - MavenRunHelper
        - com.yiycf.plugins.mavenDependencyHelper
      plugins_disabled: 
        - Ant Tracer Plugin
        - AntSupport
        - CFML Support
        - ClearcasePlugin
        - CloudBees
        - CloudFoundry
        - com.intellij.drools
        - com.intellij.flex
        - com.intellij.jboss.arquillian
        - com.intellij.jboss.core
        - com.intellij.jbpm
        - com.intellij.seam
        - com.intellij.seam.pageflow
        - com.intellij.seam.pages
        - com.intellij.struts2
        - com.intellij.tapestry
        - com.jetbrains.plugins.asp
        - CVS
        - DevKit
        - Geronimo
        - GlassFish
        - hg4idea
        - J2ME
        - JBoss
        - JSR45Plugin
        - OpenShift
        - org.jetbrains.plugins.javaFX
        - org.jetbrains.plugins.rest
        - PerforceDirectPlugin
        - Resin
        - StrutsAssistant
        - Subversion
        - TFS
        - Weblogic
        - WebSphere
        - ZKM
    vscode:
      settings: {
        'cSpell.language': 'en,pt,pt_BR',
        'cSpell.diagnosticLevel': 'Warning',
        'editor.minimap.enabled': 'true',
        'editor.suggestSelection': 'first',
        'editor.tabSize': 4,
        'java.configuration.checkProjectSettingsExclusions': true,
        'javascript.preferences.quoteStyle': 'single',
        'prettier.jsxSingleQuote': true,
        'prettier.singleQuote': true,
        'typescript.preferences.quoteStyle': 'single',
        'vetur.format.defaultFormatterOptions': {
          'prettier': {
            'singleQuote': true
          }
        },
        'vsintellicode.modify.editor.suggestSelection': 'automaticallyOverrodeDefaultValue',
        'workbench.colorTheme': 'Default Dark+',
        'workbench.editor.enablePreview': true,
        'workbench.startupEditor': 'newUntitledFile',
        'editor.rulers': [80,120]
      }
      extensions:
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - eg2.vscode-npm-script
        - esbenp.prettier-vscode
        - ms-azuretools.vscode-docker
        - ms-python.python
        - octref.vetur
        - vscjava.vscode-java-pack
        - streetsidesoftware.code-spell-checker
        - shd101wyy.markdown-preview-enhanced
        - streetsidesoftware.code-spell-checker-portuguese-brazilian
        - yzhang.markdown-all-in-one
        - betterthantomorrow.calva-spritz

