---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks, it must be the same one used to login into your computer
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 

  playbooks: 
    sshkey: false 
    ssh: false
    vscode: false
    git: false
    terminator: false
    zsh: false
    ohmyzsh: false 
    tmux: false
    spotify: false
    java: false 
    gitlfs: false
    tig: false
    maven: false 
    golang: false 
    nodejs: false 
    yarn: false
    bazel: false
    rvm: false
    intellij: false 
    docker: false 
    google_cloud_sdk: false
    redis: false
    postman: false
    protobuf: false 
    zoom: false
    forticlient: false
    slack: false
    beyondcompare: false
    chrome: false
    firefox: false
    vlc: false
    flameshot: false
    htop: false
    keepassxc: false
    virtualbox: false
    pcloud: false

  tools:
    ohmyzsh:
      theme: 
        name: "powerlevel10k/powerlevel10k"
        link: https://github.com/romkatv/powerlevel10k.git
      plugins:
        - gitfast
        - git
        - docker
        - docker-compose
        - zsh-syntax-highlighting
        - zsh-autosuggestions

    java: 
      # Intellij's playbook uses both version, so don't remove them
      versions:
        - name: 8
          version: '8'
          default: no
        - name: 11 
          version: '11'
          default: yes
    gitlfs:
      version: '2.13.2'
    tig:
      version: '2.5.3'
    maven:
      version: '3.8.3'
    bazel:
      version: '4.0.0'
      sha256: 'sha256:7bee349a626281fc8b8d04a7a0b0358492712377400ab12533aeb39c2eb2b901'
    golang:
      version: '1.16.2'
      sha256sum: '542e936b19542e62679766194364f45141fde55169db2d8d01046555ca9eb4b8'
      path: '$HOME/workspace-go'
    node:
      version: '14.x'
    rvm:
      ruby:
        versions: 
          - ruby
          - 2.6.6
    docker_compose:
      version: '1.26.0'
    pcloud: ## GET THE URL ON THE PCLOUD SITE. THE DOWNLOAD LINK HAS AN EXPIRATION DATE ##
      url: 
    google_cloud_sdk:
      version: '357.0.0'
      components: pubsub-emulator app-engine-java beta
    protobuf:
      version: '3.10.0'
    slack:
      version: '4.14.0'
    forticlient:
      version: '6.4.3.0959'
    beyondcompare:
      version: '4.3.7.25118'
    intellij:
      version: '2021.2.3'
      edition: ultimate # ultimate or community
      # You can get the sha256 at this link https://confluence.jetbrains.com/display/IDEADEV/Latest+builds or at external_roles/gantsign.intellij/vars/versions
      sha256: '16929fd22b84b400d0b9e24fd356dd2e7a614511a2d779ee37082c90df179c25'
      default_jdk: '11'
      style_guide_name: 'GoogleStyle - Custom'
      style_guide_path: 'https://raw.githubusercontent.com/kamylaep/code-style/master/intellij-java-google-style-custom.xml'
      plugins: 
        #- Pythonid
        #- org.jetbrains.plugins.ruby
        - org.intellij.scala
        - net.codestats.plugin.atom.intellij
        - MavenRunHelper
        - Key Promoter X
        - com.yiycf.plugins.mavenDependencyHelper
        - com.google.idea.bazel.ijwb
      plugins_disabled: 
        - Ant Tracer Plugin
        - AntSupport
        - CFML Support
        - ClearcasePlugin
        - CloudBees
        - CloudFoundry
        - com.intellij.drools
        - com.intellij.flex
        - com.intellij.jboss.arquillian
        - com.intellij.jboss.core
        - com.intellij.jbpm
        - com.intellij.seam
        - com.intellij.seam.pageflow
        - com.intellij.seam.pages
        - com.intellij.struts2
        - com.intellij.tapestry
        - com.jetbrains.plugins.asp
        - CVS
        - DevKit
        - Geronimo
        - GlassFish
        - hg4idea
        - J2ME
        - JBoss
        - JSR45Plugin
        - OpenShift
        - org.jetbrains.plugins.javaFX
        - org.jetbrains.plugins.rest
        - PerforceDirectPlugin
        - Resin
        - StrutsAssistant
        - Subversion
        - TFS
        - Weblogic
        - WebSphere
        - ZKM
    vscode:
      settings: {
        'cSpell.language': 'en,pt,pt_BR',
        'cSpell.diagnosticLevel': 'Warning',
        'editor.minimap.enabled': 'false',
        'editor.suggestSelection': 'first',
        'editor.tabSize': 4,
        'java.configuration.checkProjectSettingsExclusions': false,
        'javascript.preferences.quoteStyle': 'single',
        'prettier.jsxSingleQuote': true,
        'prettier.singleQuote': true,
        'typescript.preferences.quoteStyle': 'single',
        'vetur.format.defaultFormatterOptions': {
          'prettier': {
            'singleQuote': true
          }
        },
        'vsintellicode.modify.editor.suggestSelection': 'automaticallyOverrodeDefaultValue',
        'workbench.colorTheme': 'Default Dark+',
        'workbench.editor.enablePreview': false,
        'workbench.startupEditor': 'newUntitledFile',
        'editor.rulers': [80,120]
      }
      extensions:
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - eg2.vscode-npm-script
        - esbenp.prettier-vscode
        - ms-azuretools.vscode-docker
        - ms-python.python
        - octref.vetur
        - vscjava.vscode-java-pack
        - streetsidesoftware.code-spell-checker
        - shd101wyy.markdown-preview-enhanced
        - streetsidesoftware.code-spell-checker-portuguese-brazilian
        - yzhang.markdown-all-in-one
        - vscoss.vscode-ansible
