---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 
  os: 
    wallpaper_name: falcon.jpg
    greeter_background_name: soyuz.jpg
    lock_after: 30
  

  playbooks: 
    sshkey: false 
    ssh: false
    wallpaper: false
    display_manager: false
    