---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks, it must be the same one used to login into your computer
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 

  playbooks: 
    sshkey: false 
    ssh: false
    vscode: false
    git: false
    terminator: false
    zsh: false
    ohmyzsh: false 
    tmux: false
    spotify: false
    java: false 
    gitlfs: false
    tig: false
    maven: false 
    golang: false 
    nodejs: false 
    yarn: false
    bazel: false
    rvm: false
    intellij: false 
    docker: false 
    pcloud: false
    google_cloud_sdk: false
    redis: false
    postman: false
    protobuf: false 
    zoom: false
    forticlient: false
    slack: false
    beyondcompare: false
    chrome: false
    firefox: false
    vlc: false
    flameshot: false
    htop: false
    keepassxc: false
    virtualbox: false
    solaar: false
    python: false
    jq: false

  tools:
    ohmyzsh:
      theme: 
        name: "powerlevel10k/powerlevel10k"
        link: https://github.com/romkatv/powerlevel10k.git
      plugins:
        - gitfast
        - git
        - docker
        - docker-compose
        - zsh-syntax-highlighting
        - zsh-autosuggestions

    java: 
      # Intellij's playbook uses both version, so don't remove them
      versions:
        - name: 8
          version: '8'
          default: no
        - name: 11 
          version: '11'
          default: no
        - name: 17 
          version: '17'
          default: yes
    gitlfs:
      version: '3.3.0'
    tig:
      version: '2.5.4'
    maven:
      version: '3.9.1'
    bazel:
      version: '4.2.1'
      sha256: 'sha256:1a4f3a3ce292307bceeb44f459883859c793436d564b95319aacb8af1f20557c'
    golang:
      version: '1.20.5'
      sha256sum: 'd7ec48cde0d3d2be2c69203bc3e0a44de8660b9c09a6e85c4732a3f7dc442612'
      path: '$HOME/workspace-go'
    node:
      version: '16.x'
    rvm:
      ruby:
        versions: 
          - ruby
          - 2.6.6
    docker_compose:
      version: '1.29.2'
    pcloud: ## GET THE URL ON THE PCLOUD SITE. THE DOWNLOAD LINK HAS AN EXPIRATION DATE ##
      url: 
    google_cloud_sdk:
      version: '365.0.0'
      components: pubsub-emulator app-engine-java beta
    protobuf:
      version: '3.10.0'
    slack:
      version: '4.22.0'
    forticlient:
      version: '7.0.0.0018'
    beyondcompare:
      version: '4.4.6.27483'
    intellij:
      version: '2023.1.3'
      edition: community # ultimate or community
      sha256: '336ec81b78645349e0b476047e2d1993ed3f1c571f8961565a3e47fe5c9c02bf'
      default_jdk: '17'
      style_guide_name: 'GoogleStyle - Custom'
      style_guide_path: 'https://raw.githubusercontent.com/kamylaep/code-style/master/intellij-java-google-style-custom.xml'
      plugins: 
        - org.intellij.scala
        - net.codestats.plugin.atom.intellij
        - MavenRunHelper
        - com.yiycf.plugins.mavenDependencyHelper
      plugins_disabled: 
        - Ant Tracer Plugin
        - AntSupport
        - CFML Support
        - ClearcasePlugin
        - CloudBees
        - CloudFoundry
        - com.intellij.drools
        - com.intellij.flex
        - com.intellij.jboss.arquillian
        - com.intellij.jboss.core
        - com.intellij.jbpm
        - com.intellij.seam
        - com.intellij.seam.pageflow
        - com.intellij.seam.pages
        - com.intellij.struts2
        - com.intellij.tapestry
        - com.jetbrains.plugins.asp
        - CVS
        - DevKit
        - Geronimo
        - GlassFish
        - hg4idea
        - J2ME
        - JBoss
        - JSR45Plugin
        - OpenShift
        - org.jetbrains.plugins.javaFX
        - org.jetbrains.plugins.rest
        - PerforceDirectPlugin
        - Resin
        - StrutsAssistant
        - Subversion
        - TFS
        - Weblogic
        - WebSphere
        - ZKM
    vscode:
      settings: {
        'cSpell.language': 'en,pt,pt_BR',
        'cSpell.diagnosticLevel': 'Warning',
        'editor.minimap.enabled': 'false',
        'editor.suggestSelection': 'first',
        'editor.tabSize': 4,
        'java.configuration.checkProjectSettingsExclusions': false,
        'javascript.preferences.quoteStyle': 'single',
        'prettier.jsxSingleQuote': true,
        'prettier.singleQuote': true,
        'typescript.preferences.quoteStyle': 'single',
        'vetur.format.defaultFormatterOptions': {
          'prettier': {
            'singleQuote': true
          }
        },
        'vsintellicode.modify.editor.suggestSelection': 'automaticallyOverrodeDefaultValue',
        'workbench.colorTheme': 'Default Dark+',
        'workbench.editor.enablePreview': false,
        'workbench.startupEditor': 'newUntitledFile',
        'editor.rulers': [80,120]
      }
      extensions:
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - eg2.vscode-npm-script
        - esbenp.prettier-vscode
        - ms-azuretools.vscode-docker
        - ms-python.python
        - octref.vetur
        - vscjava.vscode-java-pack
        - streetsidesoftware.code-spell-checker
        - shd101wyy.markdown-preview-enhanced
        - streetsidesoftware.code-spell-checker-portuguese-brazilian
        - yzhang.markdown-all-in-one
