---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: 
    # REQUIRED: used by atom, vscode, intellij, sshkey and oh-my_zsh playbooks
    username: 
    # REQUIRED: used by the git and sshkey playbook
    email: 
  os: 
    wallpaper_name: falcon.jpg
    greeter_background_name: soyuz.jpg
    lock_after: 30
    keyboard_shortcuts:
      - shortcut: "<Alt><Super>Down"
        action: "amixer set Master 5%-"
      - shortcut: "<Alt><Super>Up"
        action: "amixer set Master 5%+"
      - shortcut: "<Alt><Super>Right"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
      - shortcut: "<Alt><Super>Left"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
      - shortcut: "<Alt><Super>Return"
        action: "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
      - shortcut: "<Super>l"
        action: "xflock4"

  playbooks: 
    sshkey: false 
    ssh: false
    wallpaper: false
    display_manager: false
    keyboard_shortcuts: false
    autolock: false
    packages: false 
    packages_dpkg: false

  packages_debian: 
    - baobab
    - caja
    - chromium-browser
    - firefox
    - flameshot
    - htop
    - keepassxc
    - python3-pip
    - remmina
    - terminator
    - transmission
    - vim
    - vlc
    - zsh
  
  packages_dpkg:
    - https://www.scootersoftware.com/bcompare-4.3.2.24472_amd64.deb
    - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
    - https://download.nomachine.com/download/6.9/Linux/nomachine_6.9.2_1_amd64.deb