---
- hosts: all

  roles:
    - role: ../../external-roles/gantsign.oh-my-zsh
      users:
        - username: '{{ my.data.username }}'
          oh_my_zsh:
            theme: '{{ my.tools.ohmyzsh.theme }}'
            plugins: '{{ my.tools.ohmyzsh.plugins }}'

  tasks:
    - name: Configuring ZPROFILE to source /etc/profile.d scripts
      blockinfile:
        path: /etc/zsh/zprofile
        block: |
          for f in /etc/profile.d/*.sh; do 
              source "$f" 
          done
      become: yes
      when: ansible_env['XDG_CURRENT_DESKTOP'] == "KDE"