---
- hosts: all

  roles:
    - role: ../../external-roles/gantsign.oh-my-zsh
      users:
        - username: '{{ my.data.username }}'
          oh_my_zsh:
            theme: frisk
            plugins:
              - gitfast
              - docker
              - docker-compose
              - heroku
              - helm
              - kubectl
              - minikube
              - mvn
              - ansible
              - golang
              - gradle
              - node
              - npm
              - npx
              - pip
              - pipenv
              - python
              - tig
              - virtualenv
              - rvm
              - ruby
              - rails

  tasks:
    - name: Configuring ZPROFILE to source /etc/profile.d scripts
      blockinfile:
        path: /etc/zsh/zprofile
        block: |
          for f in /etc/profile.d/*.sh; do 
              source "$f" 
          done
      become: yes
      when: ansible_env['XDG_CURRENT_DESKTOP'] == "KDE"