---
- hosts: all

  tasks:
    - name: Installing FORTI CLIENT VPN dependencies
      package:
        name: gnome-keyring
      become: yes

    - name: Install prerequisites for Ansible to install .deb via apt module
      apt:
        name: xz-utils

    - name: Installing FORTI CLIENT VPN
      apt:
        deb: "https://filestore.fortinet.com/forticlient/downloads/forticlient_vpn_{{ my.tools.forticlient.version }}_amd64.deb"
      become: yes