---
- hosts: all

  tasks:
        
    - name: Downloading REDIS
      unarchive:
        src: http://download.redis.io/redis-stable.tar.gz
        dest: /tmp/
        remote_src: true
    
    - name: Installing REDIS dependencies
      package:
        name: "{{ item }}"
      with_items:
        - make
        - build-essential
      become: yes

    - name: Running REDIS make install
      make:
        chdir: /tmp/redis-stable
        target: install
      become: yes