---
- hosts: all

  tasks:
    - name: Installing SLACK
      apt:
        deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ my.tools.slack.version }}-amd64.deb"
      become: yes