---
- import_playbook: partials/config/variables-validation.yml

- import_playbook: partials/personal/sshkey.yml
  when: my.playbooks.sshkey | bool

- import_playbook: partials/tools/ssh.yml
  when: my.playbooks.ssh | bool

- import_playbook: partials/config/xfce4/wallpaper.yml
  when: my.playbooks.wallpaper | bool
