---
- import_playbook: partials/variables-validation.yml

- import_playbook: partials/sshkey.yml
  when: my.playbooks.sshkey | bool

- import_playbook: partials/ssh.yml
  when: my.playbooks.ssh | bool

- import_playbook: partials/vscode.yml
  when: my.playbooks.vscode | bool

- import_playbook: partials/git.yml
  when: my.playbooks.git | bool or my.playbooks.gitlfs | bool or my.playbooks.tig | bool | bool or my.playbooks.ohmyzsh | bool or my.playbooks.tmux | bool

- import_playbook: partials/terminator.yml
  when: my.playbooks.terminator | bool

- import_playbook: partials/zsh.yml
  when: my.playbooks.zsh | bool or my.playbooks.ohmyzsh | bool

- import_playbook: partials/oh-my-zsh.yml
  when: my.playbooks.ohmyzsh | bool or my.playbooks.zsh | bool

- import_playbook: partials/tmux.yml
  when: my.playbooks.tmux | bool 

- import_playbook: partials/spotify.yml
  when: my.playbooks.spotify | bool

- import_playbook: partials/java.yml
  when: my.playbooks.java | bool or my.playbooks.maven | bool or my.playbooks.intellij | bool


- import_playbook: partials/git-lfs.yml
  when: my.playbooks.gitlfs | bool

- import_playbook: partials/tig.yml
  when: my.playbooks.tig | bool

- import_playbook: partials/maven.yml
  when: my.playbooks.maven | bool or my.playbooks.intellij | bool
  
- import_playbook: partials/golang.yml
  when: my.playbooks.golang | bool or my.playbooks.bazel | bool
  
- import_playbook: partials/nodejs.yml
  when: my.playbooks.nodejs | bool
  
- import_playbook: partials/yarn.yml
  when: my.playbooks.yarn | bool

- import_playbook: partials/bazel.yml
  when: my.playbooks.bazel | bool

- import_playbook: partials/rvm.yml
  when: my.playbooks.rvm | bool

- import_playbook: partials/intellij.yml
  when: my.playbooks.intellij | bool

- import_playbook: partials/docker.yml
  when: my.playbooks.docker | bool

- import_playbook: partials/pcloud.yml
  when: my.playbooks.pcloud | bool

- import_playbook: partials/google-cloud-sdk.yml
  when: my.playbooks.google_cloud_sdk | bool

- import_playbook: partials/redis.yml
  when: my.playbooks.redis | bool

- import_playbook: partials/postman.yml
  when: my.playbooks.postman | bool

- import_playbook: partials/protobuf.yml
  when: my.playbooks.protobuf | bool

- import_playbook: partials/zoom.yml
  when: my.playbooks.zoom | bool

- import_playbook: partials/forticlient.yml
  when: my.playbooks.forticlient | bool

- import_playbook: partials/slack.yml
  when: my.playbooks.slack | bool

- import_playbook: partials/beyond-compare.yml
  when: my.playbooks.beyondcompare | bool

- import_playbook: partials/chrome.yml
  when: my.playbooks.chrome | bool

- import_playbook: partials/firefox.yml
  when: my.playbooks.firefox | bool

- import_playbook: partials/vlc.yml
  when: my.playbooks.vlc | bool

- import_playbook: partials/flameshot.yml
  when: my.playbooks.flameshot | bool

- import_playbook: partials/htop.yml
  when: my.playbooks.htop | bool

- import_playbook: partials/virtualbox.yml
  when: my.playbooks.virtualbox | bool
