---
- import_playbook: partials/config/variables-validation.yml

- import_playbook: partials/personal/sshkey.yml
  when: my.playbooks.sshkey | bool

- import_playbook: partials/tools/ssh.yml
  when: my.playbooks.ssh | bool

- import_playbook: partials/tools/lastpass.yml
  when: my.playbooks.lastpass | bool

- import_playbook: partials/config/xfce4/wallpaper.yml
  when: ansible_env['XDG_CURRENT_DESKTOP'] == "XFCE" and my.playbooks.wallpaper | bool

- import_playbook: partials/config/xfce4/display-manager.yml
  when: ansible_env['XDG_CURRENT_DESKTOP'] == "XFCE" and my.playbooks.display_manager | bool

- import_playbook: partials/config/xfce4/keyboard-shortcuts.yml
  when: ansible_env['XDG_CURRENT_DESKTOP'] == "XFCE" and my.playbooks.keyboard_shortcuts | bool

- import_playbook: partials/config/xfce4/autolock.yml
  when: ansible_env['XDG_CURRENT_DESKTOP'] == "XFCE" and my.playbooks.autolock | bool

- import_playbook: partials/package-manager/packages.yml
  when: my.playbooks.packages | bool

- import_playbook: partials/package-manager/packages_dpkg.yml
  when: my.playbooks.packages_dpkg | bool

- import_playbook: partials/dev/editors/vscode.yml
  when: my.playbooks.vscode | bool

- import_playbook: partials/shell/oh-my-zsh.yml
  when: my.playbooks.ohmyzsh | bool

- import_playbook: partials/tools/expressvpn.yml
  when: my.playbooks.expressvpn | bool

- import_playbook: partials/media/spotify.yml
  when: my.playbooks.spotify | bool

- import_playbook: partials/dev/java.yml
  when: my.playbooks.java | bool

- import_playbook: partials/dev/git.yml
  when: my.playbooks.git | bool

- import_playbook: partials/dev/tig.yml
  when: my.playbooks.tig | bool

- import_playbook: partials/dev/maven.yml
  when: my.playbooks.maven | bool
  
- import_playbook: partials/dev/golang.yml
  when: my.playbooks.golang | bool
  
- import_playbook: partials/dev/nodejs.yml
  when: my.playbooks.nodejs | bool
  
- import_playbook: partials/dev/yarn.yml
  when: my.playbooks.yarn | bool

- import_playbook: partials/dev/bazel.yml
  when: my.playbooks.bazel | bool

- import_playbook: partials/dev/rvm.yml
  when: my.playbooks.rvm | bool

- import_playbook: partials/dev/ides/intellij.yml
  when: my.playbooks.intellij | bool

- import_playbook: partials/dev/pipenv.yml
  when: my.playbooks.pipenv | bool

- import_playbook: partials/dev/docker.yml
  when: my.playbooks.docker | bool

- import_playbook: partials/tools/toggl.yml
  when: my.playbooks.toggl | bool

- import_playbook: partials/tools/pcloud.yml
  when: my.playbooks.pcloud | bool

- import_playbook: partials/dev/google-cloud-sdk.yml
  when: my.playbooks.google_cloud_sdk | bool
  
- import_playbook: partials/dev/sdkman.yml
  when: my.playbooks.sdkman | bool

- import_playbook: partials/tools/postman.yml
  when: my.playbooks.postman | bool

- import_playbook: partials/dev/gradle.yml
  when: my.playbooks.gradle | bool
  
- import_playbook: partials/dev/editors/atom.yml
  when: my.playbooks.atom | bool

- import_playbook: partials/dev/editors/sublime.yml
  when: my.playbooks.sublime | bool

- import_playbook: partials/dev/ides/eclipse.yml
  when: my.playbooks.eclipse | bool

- import_playbook: partials/dev/protobuf.yml
  when: my.playbooks.protobuf | bool

- import_playbook: partials/dev/robo3t.yml
  when: my.playbooks.robo3t | bool

- import_playbook: partials/dev/awscli.yml
  when: my.playbooks.awscli | bool

- import_playbook: partials/dev/redis-desktop-manager.yml
  when: my.playbooks.redis_desktop_manager | bool

- import_playbook: partials/dev/kafkatool.yml
  when: my.playbooks.kafkatool | bool
