---
- import_playbook: partials/config/variables-validation.yml

- import_playbook: partials/personal/sshkey.yml
  when: my.playbooks.sshkey | bool

- import_playbook: partials/tools/ssh.yml
  when: my.playbooks.ssh | bool

- import_playbook: partials/dev/editors/vscode.yml
  when: my.playbooks.vscode | bool

- import_playbook: partials/shell/terminator.yml
  when: my.playbooks.terminator | bool

- import_playbook: partials/shell/zsh.yml
  when: my.playbooks.zsh | bool or my.playbooks.ohmyzsh | bool

- import_playbook: partials/shell/oh-my-zsh.yml
  when: my.playbooks.ohmyzsh | bool or my.playbooks.zsh | bool

- import_playbook: partials/media/spotify.yml
  when: my.playbooks.spotify | bool

- import_playbook: partials/dev/java.yml
  when: my.playbooks.java | bool or my.playbooks.maven | bool or my.playbooks.intellij | bool

- import_playbook: partials/dev/git.yml
  when: my.playbooks.git | bool or my.playbooks.gitlfs | bool or my.playbooks.tig | bool

- import_playbook: partials/dev/git-lfs.yml
  when: my.playbooks.gitlfs | bool

- import_playbook: partials/dev/tig.yml
  when: my.playbooks.tig | bool

- import_playbook: partials/dev/maven.yml
  when: my.playbooks.maven | bool or my.playbooks.intellij | bool
  
- import_playbook: partials/dev/golang.yml
  when: my.playbooks.golang | bool or my.playbooks.bazel | bool
  
- import_playbook: partials/dev/nodejs.yml
  when: my.playbooks.nodejs | bool
  
- import_playbook: partials/dev/yarn.yml
  when: my.playbooks.yarn | bool

- import_playbook: partials/dev/bazel.yml
  when: my.playbooks.bazel | bool

- import_playbook: partials/dev/rvm.yml
  when: my.playbooks.rvm | bool

- import_playbook: partials/dev/ides/intellij.yml
  when: my.playbooks.intellij | bool

- import_playbook: partials/dev/docker.yml
  when: my.playbooks.docker | bool

- import_playbook: partials/tools/pcloud.yml
  when: my.playbooks.pcloud | bool

- import_playbook: partials/dev/google-cloud-sdk.yml
  when: my.playbooks.google_cloud_sdk | bool

- import_playbook: partials/dev/redis.yml
  when: my.playbooks.redis | bool

- import_playbook: partials/tools/postman.yml
  when: my.playbooks.postman | bool

- import_playbook: partials/dev/protobuf.yml
  when: my.playbooks.protobuf | bool

- import_playbook: partials/tools/zoom.yml
  when: my.playbooks.zoom | bool

- import_playbook: partials/tools/forticlient.yml
  when: my.playbooks.forticlient | bool

- import_playbook: partials/tools/slack.yml
  when: my.playbooks.slack | bool

- import_playbook: partials/tools/beyond-compare.yml
  when: my.playbooks.beyondcompare | bool

- import_playbook: partials/tools/chrome.yml
  when: my.playbooks.chrome | bool

- import_playbook: partials/tools/firefox.yml
  when: my.playbooks.firefox | bool

- import_playbook: partials/media/vlc.yml
  when: my.playbooks.vlc | bool

- import_playbook: partials/tools/flameshot.yml
  when: my.playbooks.flameshot | bool

- import_playbook: partials/tools/htop.yml
  when: my.playbooks.htop | bool

- import_playbook: partials/tools/virtualbox.yml
  when: my.playbooks.virtualbox | bool
