---
- import_playbook: partials/config/variables-validation.yml

- import_playbook: partials/personal/sshkey.yml
  when: my.playbooks.sshkey | bool

- import_playbook: partials/tools/ssh.yml
  when: my.playbooks.ssh | bool

- import_playbook: partials/config/xfce4/wallpaper.yml
  when: my.playbooks.wallpaper | bool

- import_playbook: partials/config/xfce4/display-manager.yml
  when: my.playbooks.display_manager | bool

- import_playbook: partials/config/xfce4/keyboard-shortcuts.yml
  when: my.playbooks.keyboard_shortcuts | bool

- import_playbook: partials/config/xfce4/autolock.yml
  when: my.playbooks.autolock | bool

- import_playbook: partials/package-manager/packages.yml
  when: my.playbooks.packages | bool

- import_playbook: partials/package-manager/packages_dpkg.yml
  when: my.playbooks.packages_dpkg | bool

- import_playbook: partials/dev/editors/vscode.yml
  when: my.playbooks.vscode | bool

- import_playbook: partials/shell/oh-my-zsh.yml
  when: my.playbooks.ohmyzsh | bool

- import_playbook: partials/tools/expressvpn.yml
  when: my.playbooks.expressvpn | bool

- import_playbook: partials/media/spotify.yml
  when: my.playbooks.spotify | bool

- import_playbook: partials/dev/java.yml
  when: my.playbooks.java | bool

- import_playbook: partials/dev/git.yml
  when: my.playbooks.git | bool

- import_playbook: partials/dev/tig.yml
  when: my.playbooks.tig | bool
