---
- hosts: all
  vars:
    - eclipse_package: "eclipse-{{ my.tools.eclipse.edition }}-{{ my.tools.eclipse.version }}-{{ my.tools.eclipse.release }}-linux-gtk-x86_64.tar.gz"
    - eclipse_url: "http://mirror.math.princeton.edu/pub/eclipse//technology/epp/downloads/release/{{ my.tools.eclipse.version }}/{{ my.tools.eclipse.release }}/{{ eclipse_package }}"
    - home_path: "/usr/local/eclipse"
    - home_name: "ECLIPSE_HOME"
    - launcher_name: Eclipse
    - launcher_cmd: "{{ home_path }}/eclipse"
    - launcher_icon: "{{ home_path }}/plugins/org.eclipse.platform_4.11.0.v20190307-0500/eclipse24.png"
  tasks:

    - name: Downloading ECLIPSE
      get_url:
        url: "{{ eclipse_url }}"
        dest: '/tmp'

    - name: Creating ECLIPSE dir
      file:
        path: "{{ home_path }}"
        state: directory
      become: yes
      
    - name: Unzipping ECLIPSE
      unarchive:
        src: "/tmp/{{ eclipse_package }}"
        extra_opts:
          - "--strip-components=1"
        dest: "{{ home_path }}"
        remote_src: true
      become: yes

    - name: Setting ECLIPSE permissions
      file:
        path: "{{ home_path }}"
        owner: "{{ my.data.username }}"
        group: "{{ my.data.username }}"
        recurse: yes
      become: yes

    - name: Exporting ECLIPSE_HOME and add to PATH
      template:
        src: ../../../templates/init.sh.j2
        dest: /etc/profile.d/eclipse.sh
        backup: yes
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes

    - name: Exporting ECLIPSE menu launcher
      template:
        src: ../../../templates/app.desktop.j2
        dest: /usr/share/applications/eclipse.desktop
        backup: yes
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes