---
- hosts: all

  tasks:
    - name: Installing TOGGL
      apt:
        deb: "{{ item }}"
      with_items:
        - http://fr.archive.ubuntu.com/ubuntu/pool/universe/g/gstreamer0.10/libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb
        - "https://github.com/toggl-open-source/toggldesktop/releases/download/v{{ my.tools.toggl.version }}/toggldesktop_{{ my.tools.toggl.version }}_amd64.deb"
      become: yes