---
- hosts: all
  become: yes
 
  tasks:
    - name: Installing Debian packages
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ my.packages_debian }}"
      when: my.packages_debian is defined
