---
- hosts: all
  become: yes

  tasks:
    - name: Removing LIGHTDM-GTK
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - lightdm-gtk-greeter
        - lightdm-gtk-greeter-settings
        - light-locker

    - name: Installing SLICK-GREETER
      package:
        name: "{{ item }}"
      with_items:
        - python-gi
        - light-locker
        - light-locker-settings
        - lightdm-settings
        - slick-greeter
    
    - name: Setting GREETER background
      template:
        src: ../../../templates/slick-greeter.conf.j2
        dest: /etc/lightdm/slick-greeter.conf
        backup: yes
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'