---
- hosts: all
  vars:
    - home_dir: "/home/{{ my.data.username }}"
 
  tasks:
    - name: Installing Amazon AWS Cli
      pip: 
        name: awscli
        extra_args: --force-reinstall --upgrade --user

    - name: Creating Amazon AWS Cli configuration dir
      file:
        path: "{{ home_dir }}/.aws"
        state: directory
        owner: "{{ my.data.username }}"
        group: "{{ my.data.username }}"
        mode: 0755

    - name: 'Copying Amazon AWS CLI config'
      template:
        src: ../../templates/aws_cli_config.j2
        dest: "{{ home_dir }}/.aws/config"
        backup: yes
        owner: "{{ my.data.username }}"
        group: "{{ my.data.username }}"
        mode: '0600'
      
    - name: 'Copying Amazon AWS CLI credentials'
      template: 
        src: ../../templates/aws_cli_credentials.j2
        dest: "{{ home_dir }}/.aws/credentials"
        backup: yes
        owner: "{{ my.data.username }}"
        group: "{{ my.data.username }}"
        mode: '0600'