---
- hosts: all
  vars:
    - gcsdk_package: "google-cloud-sdk-{{ my.tools.google_cloud_sdk.version }}-linux-x86_64.tar.gz"
    - gcsdk_url: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/{{ gcsdk_package }}"
    - home_root: "/home/{{ my.data.username }}"
    - home_path: "{{ home_root }}/google-cloud-sdk"

  tasks:
    - name: Downloading GOOGLE CLOUD SDK
      get_url:
        url: "{{ gcsdk_url }}"
        dest: '/tmp'

    - name: Unzipping GOOGLE CLOUD SDK
      unarchive:
        src: "/tmp/{{ gcsdk_package }}"
        dest: "{{ home_root }}"
        remote_src: true
    
    - name: Installing GOOGLE CLOUD SDK
      shell: |
        {{ home_path }}/install.sh \
        --usage-reporting false \
        --rc-path /home/{{ my.data.username }}/.zshrc \
        --command-completion true \
        --path-update true \
        --additional-components {{ my.tools.google_cloud_sdk.components }}
