---
- hosts: all
  vars:
    - robo3t_package: "robo3t-{{ my.tools.robo3t.version }}-linux-x86_64-7419c406.tar.gz"
    - robo3t_url: "https://download-test.robomongo.org/linux/{{ robo3t_package }}"
    - home_path: "/usr/local/robo3t"
    - home_name: "ROBO3T_HOME"
    - launcher_name: Robo3t
    - launcher_cmd: "{{ home_path }}/bin/robo3t"
    - launcher_icon:

  tasks:
    - name: Downloading ROBO3T
      get_url:
        url: "{{ robo3t_url }}"
        dest: '/tmp'

    - name: Creating ROBO3T dir
      file:
        path: "{{ home_path }}"
        state: directory
      become: yes
      
    - name: Unzipping ROBO3T
      unarchive:
        src: "/tmp/{{ robo3t_package }}"
        extra_opts:
          - "--strip-components=1"
        dest: "{{ home_path }}"
        remote_src: true
      become: yes
   
    - name: Setting ROBO3T permissions
      file:
        path: "{{ home_path }}"
        owner: "{{ my.data.username }}"
        group: "{{ my.data.username }}"
        recurse: yes
      become: yes

    - name: Exporting ROBO3T_HOME and add to PATH
      template:
        src: ../../templates/init.sh.j2
        dest: /etc/profile.d/robo3t.sh
        backup: yes
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes

    - name: Exporting ROBO3T menu launcher
      template:
        src: ../../templates/app.desktop.j2
        dest: /usr/share/applications/robo3t.desktop
        backup: yes
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes