---
- hosts: all
  become: yes
  
  tasks:
    - name: Adding SUBLIME repository key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Installing apt-transport-https
      apt:
        name: apt-transport-https

    - name: Selecting SUBLIME channel
      shell: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

    - name: Installing SUBLIME
      apt:
        name: sublime-text
        update-cache: yes
        autoclean: yes